In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_parquet(
    "../data/processed/uk_housing_combined.parquet"
)

In [3]:
df.shape

(6934267, 17)

In [4]:
df.head()

,Transaction_ID,Price,Date_of_Transfer,Postcode,Property_Type,Old_New,Duration,PAON,SAON,Street,Locality,Town_City,District,County,PPD_Category,Record_Status,Source_Year
0,{8CAC1318-5AA6-0253-E053-6B04A8C08E51},165000,2019-05-24 00:00,M32 0JL,S,N,F,35,NaN,STANWAY STREET,STRETFORD,MANCHESTER,TRAFFORD,GREATER MANCHESTER,A,A,2019
1,{8CAC1318-5AA7-0253-E053-6B04A8C08E51},116000,2019-06-07 00:00,L9 1DZ,T,N,F,91,NaN,BREEZE HILL,NaN,LIVERPOOL,LIVERPOOL,MERSEYSIDE,A,A,2019
2,{8CAC1318-5AA8-0253-E053-6B04A8C08E51},60000,2019-05-23 00:00,L4 0RS,T,N,F,26,NaN,CONINGSBY ROAD,NaN,LIVERPOOL,LIVERPOOL,MERSEYSIDE,A,A,2019
3,{8CAC1318-5AAA-0253-E053-6B04A8C08E51},192000,2019-05-24 00:00,WA3 1EP,D,N,L,23,NaN,ABBEY ROAD,LOWTON,WARRINGTON,WIGAN,GREATER MANCHESTER,A,A,2019
4,{8CAC1318-5AAB-0253-E053-6B04A8C08E51},166000,2019-06-07 00:00,PR1 0YA,S,N,F,4,NaN,LARCHWOOD,PENWORTHAM,PRESTON,SOUTH RIBBLE,LANCASHIRE,A,A,2019

In [5]:
df.tail()

,Transaction_ID,Price,Date_of_Transfer,Postcode,Property_Type,Old_New,Duration,PAON,SAON,Street,Locality,Town_City,District,County,PPD_Category,Record_Status,Source_Year
6934262,{38EDC0C3-0727-0F63-E063-4704A8C00424},139950,2025-05-30 00:00,BB1 2LG,T,N,F,64,NaN,BLACKAMOOR ROAD,GUIDE,BLACKBURN,BLACKBURN WITH DARWEN,BLACKBURN WITH DARWEN,A,A,2025
6934263,{38EDC0C3-0728-0F63-E063-4704A8C00424},118000,2025-05-28 00:00,FY8 3NF,F,N,L,103,FLAT 3,ST ANNES ROAD EAST,NaN,LYTHAM ST ANNES,FYLDE,LANCASHIRE,A,A,2025
6934264,{38EDC0C3-072A-0F63-E063-4704A8C00424},135000,2025-05-30 00:00,LA1 2BJ,T,N,F,74,NaN,PINFOLD LANE,NaN,LANCASTER,LANCASTER,LANCASHIRE,A,A,2025
6934265,{38EDC0C3-072B-0F63-E063-4704A8C00424},150000,2025-05-23 00:00,PR3 3TN,T,N,F,22,NaN,PARLICK AVENUE,LONGRIDGE,PRESTON,RIBBLE VALLEY,LANCASHIRE,A,A,2025
6934266,{38EDC0C3-072C-0F63-E063-4704A8C00424},207503,2025-06-13 00:00,PR2 3EL,T,N,F,9,NaN,CONWAY DRIVE,FULWOOD,PRESTON,PRESTON,LANCASHIRE,A,A,2025

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6934267 entries, 0 to 6934266
Data columns (total 17 columns):
 #   Column            Dtype
---  ------            -----
 0   Transaction_ID    str
 1   Price             int64
 2   Date_of_Transfer  str
 3   Postcode          str
 4   Property_Type     str
 5   Old_New           str
 6   Duration          str
 7   PAON              str
 8   SAON              str
 9   Street            str
 10  Locality          str
 11  Town_City         str
 12  District          str
 13  County            str
 14  PPD_Category      str
 15  Record_Status     str
 16  Source_Year       int64
dtypes: int64(2), str(15)
memory usage: 1.7 GB

In [13]:
df.isnull().sum()

(
    df.isnull().sum()
    / len(df)
    * 100
).sort_values(ascending=False)

null_summary = pd.DataFrame({
    "Null_Count": df.isnull().sum(),
    "Null_Percent":
    round(
        df.isnull().sum()
        / len(df)
        * 100,
        2
    )
})

null_summary.sort_values(
    "Null_Percent",
    ascending=False
)

                  Null_Count  Null_Percent
SAON                 6024676         86.88
Locality             4276927         61.68
Street                123881          1.79
Postcode               21483          0.31
Transaction_ID             0          0.00
Property_Type              0          0.00
Old_New                    0          0.00
Date_of_Transfer           0          0.00
Price                      0          0.00
PAON                       0          0.00
Duration                   0          0.00
Town_City                  0          0.00
District                   0          0.00
County                     0          0.00
PPD_Category               0          0.00
Record_Status              0          0.00
Source_Year                0          0.00

In [14]:
df = df.dropna(
    subset=["Postcode"]
)

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df["Date_of_Transfer"] = pd.to_datetime(
    df["Date_of_Transfer"]
)

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 6912784 entries, 0 to 6934266
Data columns (total 17 columns):
 #   Column            Dtype
---  ------            -----
 0   Transaction_ID    str
 1   Price             int64
 2   Date_of_Transfer  datetime64[us]
 3   Postcode          str
 4   Property_Type     str
 5   Old_New           str
 6   Duration          str
 7   PAON              str
 8   SAON              str
 9   Street            str
 10  Locality          str
 11  Town_City         str
 12  District          str
 13  County            str
 14  PPD_Category      str
 15  Record_Status     str
 16  Source_Year       int64
dtypes: datetime64[us](1), int64(2), str(14)
memory usage: 1.6 GB

In [22]:
df["Price"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)

In [23]:
df["Year"] = (
    df["Date_of_Transfer"]
    .dt.year
)

In [24]:
df["Month"] = (
    df["Date_of_Transfer"]
    .dt.month
)

In [25]:
df["Quarter"] = (
    df["Date_of_Transfer"]
    .dt.quarter
)

In [26]:
df["Month_Name"] = (
    df["Date_of_Transfer"]
    .dt.month_name()
)

In [27]:
property_map = {
    "D":"Detached",
    "S":"Semi-Detached",
    "T":"Terraced",
    "F":"Flat",
    "O":"Other"
}

df["Property_Type_Name"] = (
    df["Property_Type"]
    .map(property_map)
)

new_build_map = {
    "Y":"Yes",
    "N":"No"
}

df["New_Build"] = (
    df["Old_New"]
    .map(new_build_map)
)

tenure_map = {
    "F":"Freehold",
    "L":"Leasehold"
}

df["Tenure"] = (
    df["Duration"]
    .map(tenure_map)
)

In [28]:
df.isnull().sum()

Transaction_ID              0
Price                       0
Date_of_Transfer            0
Postcode                    0
Property_Type               0
Old_New                     0
Duration                    0
PAON                        0
SAON                  6009113
Street                 120284
Locality              4265775
Town_City                   0
District                    0
County                      0
PPD_Category                0
Record_Status               0
Source_Year                 0
Year                        0
Month                       0
Quarter                     0
Month_Name                  0
Property_Type_Name          0
New_Build                   0
Tenure                      0
dtype: int64

In [29]:
df["Price"].describe()

count    6.912784e+06
mean     3.868352e+05
std      1.569355e+06
min      1.000000e+00
25%      1.700000e+05
50%      2.670000e+05
75%      4.100000e+05
max      9.000000e+08
Name: Price, dtype: float64

In [30]:
df[df["Price"] <= 0]

Empty DataFrame
Columns: [Transaction_ID, Price, Date_of_Transfer, Postcode, Property_Type, Old_New, Duration, PAON, SAON, Street, Locality, Town_City, District, County, PPD_Category, Record_Status, Source_Year, Year, Month, Quarter, Month_Name, Property_Type_Name, New_Build, Tenure]
Index: []

[0 rows x 24 columns]

In [31]:
df.nlargest(
    10,
    "Price"
)

,Transaction_ID,Price,Date_of_Transfer,Postcode,Property_Type,Old_New,Duration,PAON,SAON,Street,...,PPD_Category,Record_Status,Source_Year,Year,Month,Quarter,Month_Name,Property_Type_Name,New_Build,Tenure
2135841,{1A0C5C64-0E03-7CBE-E063-4804A8C06C96},900000000,2021-03-29,TN23 7HE,O,N,F,"PENROSE HOUSE, 46",APARTMENT 1,VICTORIA ROAD,...,B,A,2021,2021,3,1,March,Other,No,Freehold
6472712,{42C129E5-920E-60A9-E063-4804A8C0C25D},793020000,2025-09-30,WC2R 2PR,O,N,F,"HOWARD HOTEL, 12",NaN,TEMPLE PLACE,...,B,A,2025,2025,9,3,September,Other,No,Freehold
472541,{06C9F488-12CE-9388-E063-4804A8C0BD98},542540820,2019-11-20,NW5 2HB,O,N,F,36,NaN,FORTESS ROAD,...,B,A,2019,2019,11,4,November,Other,No,Freehold
490980,{0B853950-EFE4-69A5-E063-4704A8C07DAC},494400000,2019-03-08,LS26 9DN,O,N,F,3,NaN,NEWMARKET LANE,...,B,A,2019,2019,3,1,March,Other,No,Freehold
490982,{0B853950-EFE6-69A5-E063-4704A8C07DAC},494400000,2019-03-08,LS26 9DN,O,N,F,3,NaN,NEWMARKET LANE,...,B,A,2019,2019,3,1,March,Other,No,Freehold
3824076,{1061746E-EF79-3C34-E063-4804A8C0F9E7},480000000,2022-09-21,WV2 2JL,O,N,F,MONMORE HOUSE,NaN,COOPER STREET,...,B,A,2022,2022,9,3,September,Other,No,Freehold
3841489,{1061746E-E127-3C34-E063-4804A8C0F9E7},480000000,2022-09-29,WV2 2JH,O,N,F,SUTHERLAND HOUSE,NaN,SUTHERLAND AVENUE,...,B,A,2022,2022,9,3,September,Other,No,Freehold
3845467,{1061746E-E221-3C34-E063-4804A8C0F9E7},480000000,2022-09-21,WV2 2JQ,O,N,F,SUTHERLAND SAW MILLS,NaN,SUTHERLAND AVENUE,...,B,A,2022,2022,9,3,September,Other,No,Freehold
3941676,{FD226036-9858-4CB7-E053-4804A8C00430},429000000,2022-04-22,WC1B 4JB,O,N,F,VICTORIA HOUSE,NaN,SOUTHAMPTON ROW,...,B,A,2022,2022,4,2,April,Other,No,Freehold
2407982,{E073986C-2B5A-2134-E053-6C04A8C0233B},421364142,2021-05-28,E1 8EP,O,N,F,"BEAGLE HOUSE, 1",NaN,BRAHAM STREET,...,B,A,2021,2021,5,2,May,Other,No,Freehold

In [32]:
df.to_parquet(
    "../data/processed/uk_housing_cleaned.parquet",
    index=False
)

In [33]:
test = pd.read_parquet(
    "../data/processed/uk_housing_cleaned.parquet"
)

test.shape

(6912784, 24)